FROM node:8

# Create app directory.
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copy everything else. package*.json copy is done seperately so that it can be
# cached and not rebuilt if it is not changed.
COPY . .

ENV NODE_ENV test

ENV DATABASE_HOST mysql
ENV DATABASE_DB_NAME hybotdb
ENV DATABASE_USER hybot
ENV DATABASE_PASSWORD hybot

# https://dev.to/hugodias/wait-for-mongodb-to-start-on-docker-3h8b
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && npm test
